server:
  port: 8080
  servlet:
    context-path: /qaute

spring:
  application:
    name: QAUTE
  thymeleaf:
    cache=false:
  datasource:
    url: "jdbc:mysql://localhost:3306/qaute"
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "Ol4TrKY5pNZf+zUjfsgMcjA+7ZphkCRs61AFHtDW/Aq/bmz9QASBYYM/mzAg7dZ5"
  valid-duration: 30 #in seconds
  refresh-duration: 300 #in seconds