server:
  port: 8080
  servlet:
    context-path: /qaute

spring:
  application:
    name: QAUTE
  thymeleaf:
    cache=false:
  datasource:
    url: "jdbc:mysql://localhost:3306/qaute"
    username: root
    password: Quangle2005@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
      host: smtp.gmail.com
      port: 587
      username: lmht312113@gmail.com
      password: cgou vhkl hxop sedj
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
jwt:
  signerKey: "Ol4TrKY5pNZf+zUjfsgMcjA+7ZphkCRs61AFHtDW/Aq/bmz9QASBYYM/mzAg7dZ5"
  valid-duration: 60 #in seconds
  refresh-duration: 300 #in seconds